### ISSUE TITLE
Геометријски ред, штампарске грешке, референцирање

### ISSUE THREAD

**Issue by budjen-jovan** [djokicd/zbirka-sis#10]
У фусноти 4 на 5. страни стоји сума геометријског реда са границама ±\infty, требало би од 0 до +\infty

У решењу 26. задатка под (б), остало је да је систем *бибо* стабилан (не BIBO него бибо). Одмах ту после стоји услов *конверге(н)ције*, требало би додати у спелчекер.

У решењу 27. задатка није разрешена референца (одмах испод 27.1)

**Comment by djokicd** [comment]
Footnote će biti rešen kada napišem taj zadatak :)
