### ISSUE TITLE
Greska grafika u zadatku 2

### ISSUE THREAD

**Issue by NikolaRistanovic** [djokicd/zbirka-sis#15]
Graficki prikaz resenja 2. zadatka i dobijeno resenje u vidu formule nisu saglasni.
Ustanovljeno je da je greska na grafiku(mera dirakovih impulsa treba biti promenjena sa 1 na 1/2).
Takodje je pozeljno pojasnjenje za pristup radu kada se dirakov delta impuls nalazi u kompoziciji drugih funkcija.

**Comment by budjen-jovan** [comment]
Лепо објашњење композиције дирака са функцијама има на [линку](https://math.stackexchange.com/questions/276583/dirac-delta-function-of-a-function), ал би требало дефинитивно да се појасни или бар остави израз

**Comment by djokicd** [comment]
Ovo će definitivno biti diskutovano na času.

**Comment by djokicd** [comment]
Napisao sam kratko rešenje iznova koje se nadam da je sada jasnije.
