### ISSUE TITLE
Uocene stamparske greske

### ISSUE THREAD

**Issue by budjen-jovan** [djokicd/zbirka-sis#2]
README - *rezpozitorijumu* (u prvom pasusu)

README - nekonzistentno veliko slovo autor/Autor (u prvom pasusu)

README - *Signal* i sistemi

README - Prijavljivanje gresaka u tekstu - *materijli*

1.1, 1. zadatak, d) *diskretnan*

1.1, 1. zadatak đ) *praovougaonu*

1.1, 12. zadatak, prema definiciji *perne* i neparne komponente (izmedju jednacina 12.2 i 12.3)

1.1, 13. zadatak, *pozante* konstante (u tekstu zadatka)

1.1, 16. zadatak, resenje a), *jer je osnovni periodi sabiraka racionalno samerljivi* (jer su osnovni periodi sabiraka racionalno samerljivi?)

1.1, 17. zadatak, *Ako data* sekvenca (fali je)

1.2, 22. zadatak, definicija stacionarnosti - vremenski *invarijentan/nepromnljiv*

1.2, 26. zadatak, resenje, \ref nije razresen (iznad 26.2)

1.2, 27. zadatak, jednacinom *obliika* (u tekstu zadatka)

1.2, 27. zadatak, fusnota 9, eksponencijalna funkcija jeste jedina jednaka svom izvodu, ali do na multiplikativnu konstantu, inace nedostaje f(x) = 0

1.2, 28. zadatak, Odrediti *sopstevni* odziv (odmah na kraju teksta)

2.1, 32. zadatak, poslednja recenica resenja - usled *kasenjenja*

2.1, 33. zadatak, resenje a) napon asimptotski *rasatao*

2.1, 33. zadatak, resenje b) Razvoj u *Firurijeov* red

2.1, 34. zadatak, resenje b) *Primenimo pravilo izvoda dobija se* rezultat (primenom pravila izvoda?)

5.1, 38. zadatak, resenje, *funckijom* prenosa (iznad 38.3)

6.1, 39. zadatak, pomoc, Referentni smerovi *brina* blokova

Dodatak B4 (NPS), karakteristike sistema... (izlazi sa stranice), 46. strana

**Comment by djokicd** [comment]
1.1 17. Ако дата секвенца, , представља основни период (не треба „је“)
1.2 27. Заменио сам реч "једнака" са "сразмерна"
Остало решено, хвала :)
