### ISSUE TITLE
zadaci 10 i 11

### ISSUE THREAD

**Issue by sokan02** [djokicd/zbirka-sis#22]
Slika za zadatak 10 (10.1) i resenje zadatka 11 ti se medjusobno preplicu, tj ide deo resenja 11 pa slika 10.1 pa nastavak resenja

**Comment by djokicd** [comment]
Zato svaka slika ima svoj broj. To samo po sebi nije problem - a takvo uređivanje ima smisla uraditi tek na kraju, kada je kompletan sadržaj složen :) 
Ručno preslaganje u ovom trenutku je malo besmisleno jer bi moralo opet da se radi čim se nešto promeni.

**Comment by sokan02** [comment]
al mozes samo da mu stavis [H] i da ti prosto ostane fiksirano gde treba da bude

**Comment by djokicd** [comment]
Jeste, i onda imaš pola strane prazno :) 
Bolje da se popuni gušće, a brojevima se pozivaš na slike - tome služe.
