### ISSUE TITLE
27. i 28. zadatak stamparske greske, 30. zadatak grafik

### ISSUE THREAD

**Issue by budjen-jovan** [djokicd/zbirka-sis#24]
U postavci 27. zadatka stoji $P(\textrm{D}) y(t) = x(t)$ umesto $y(t) = P(\textrm{D}) x(t)$ greskom (dalje resenje je sve po ovom drugom)
U resenju kod smene $e^{st}, \\; s = j\omega$ fali 0 u indeksu (dalje je sve $j \omega_0$)

U resenju 28. zadatka, ispod jednacine 28.1 (iz izraza (28.1) je...) stoji $\upphi'(0) = \Phi_0$ umesto $\upphi(0) = \Phi_0$ (visak izvod)
U resenju pod (v) -- a podeoci (su) razmaknuti za po tacno $\pi/12$, fali "su".

U 30. zadatku je u tekstu $i_L$ dok je na grafiku $i_{\textrm{L}}$ (uspravno L u indeksu). Sudeci po 31. zadatku gde su i u tekstu i na grafiku uspravni indeksi, verovatno i ovde treba da se namesti u tekstu uspravan indeks. Takodje na konto 27. zadatka, bilo bi lepo sa stanovista konvencije uzeti konzistentno $\omega$ ili $\omega_0$ za osnovnu ucestanost kada su prostoperiodicne pobude.

**Comment by sokan02** [comment]
meni se cini da je ovo za 27 svakako P(D)y(t) = x(t), ali da je posle greska da je P(D)y(t) = xr(t) + j*xi(t)

P.S. izvinjavam se na izostanku latex slova, ali sam na telefonu

**Comment by budjen-jovan** [comment]
Treba ipak $P(\mathrm{D}) y(t) = x(t)$. Logika stoji, i dalje se moze razdvojiti na realni i imaginarni deo posebno, ali je u ovoj formi dubiozno napisano. Krajnje resenje je okej.

Trebalo bi nesto otprilike kao
$P(\mathrm{D}) y(t) = x(t)$

$y_p(t) = \dfrac{\exp{j\omega_0 t}}{P(j \omega_0)}$

$P(\mathrm{D}) \left( y_r(t) + j y_i(t) \right) = x_r(t) + j x_i(t)$

Sto se dalje raspada onda na dva nezavisna sistema diferencijalnih jednacina
$P(\mathrm{D}) y_r(t) = x_r(t)$
$P(\mathrm{D}) y_i(t) = x_i(t)$

(skracivanjem $j$ kod imaginarnog dela jer evidentno $j \neq 0$)

Definitivno je uvedena regresija sa #25, prepravljam u toku danas

**Comment by budjen-jovan** [comment]
Решено све сем последње ставке на мерге
