### ISSUE TITLE
Штампарске грешке, форматирање, стилизација слика

### ISSUE THREAD

**Issue by budjen-jovan** [djokicd/zbirka-sis#3]
1.1, 3. задатак, поставка - *Делта* импулса (у остатку текста је Диракових импулса, Диракових делта импулса или само делта импулса (мало слово))
1.1, 3. задатак, решење - добијена струја *кондензаора*
1.1, 18. задатак, сигнал $x_2(t)$ *учестности* $f_2$
1.2, 22. задатак, решење, трећа тачка - Систем је стационаран (тј. временски инваријантан/*непромнљив*)
1.2, 22. задатак, решење, а), друга тачка у *BIBOs* смислу
1.2, 31. задатак, решење г), на самом крају после крајњег решења виси додатно *i*
1.2, 32. задатак, решење а), ознака фусноте 10 је одвојена
2.1, 35. задатак, решење, последњи пасус -  ресетује напон *кондентора*
2.1, 36. задатак, решење б), *Применимом* правила извода
4.1, 38. задатак, фуснота 21 прелази на две стране (ово је можда и циљано), Полазећи од израза за *струја*, ..., Заменом *ову* кондензатора
4.1, 38. задатак, решење б), на сред реченице стоји тачка, одмах иза фусноте 25 (која је такође одвојена као и фуснота 10 (циљано?)), у истој реченици пар речи раније изражавањем збира *односо* разлике
5.1, 40. задатак, слика 40.1 је неконзистентно стилизована (вероватно није XCircuit), такође у решењу - Пошто је задовољена теорема *одбарињања*
Додатак 5, 5.1 и 5.3, уоквирене слике ивицом газе преко ознаке напона на секундару
Додатак 5, 5.4, изводи секундара излазе изван ивице, *Овај* стоји одмах до слике уместо испод (претпоследња реченица)

**Comment by djokicd** [comment]
Ćorava rabota ovo moje peglanje grešaka nakon par verzija. Nisu isti brojevi zadataka niti stranice niti brojevi fusnota. Ali mislim da sam uspeo sve da pohvatam. Slovne greške ću da rešim uvođenjem spellcheckera - uskoro.

Nekoznistentne slike nisu strašne, za sad. Nije xcircuit, nešto je i inkscape.

Nisam ni znao da fusnota može da uradi pagebreak :| Ali to je problem za kasnije. Jer latex sam slaže položaje fusnota, i to se desi, izgleda, ako je fusnota dugačka i ako bi stavljanjem cele fusnote prebacio referencu na nju na narednu stranu - što nema smisla. Sve to će biti mnogo dručije sa drugim zadacima.

**Comment by budjen-jovan** [comment]
Бајдвеј само да не оставим да виси, онај прелаз ознака ван маргине (код трафоа) је само на телефону мени изгледа, мислим да је локално код мене баг а не у пдфу. То је то углавном хвала

**Comment by budjen-jovan** [comment]
taman sam pomislio da sam poludeo hahaha
vazi se, hvala!
