### ISSUE TITLE
Задатак 61

### ISSUE THREAD

**Issue by budjen-jovan** [djokicd/zbirka-sis#37]
### Проблеми
Поставка задатка, (в) - за вредност *отпорнисти*, такође не знам шта г у суперскрипту $v_\textrm{U}^{(\textrm{г})}$ треба да представља али ако је по индексу тачке, онда није г

Решење (а) - сам почетак, испод једначине 61.1, $Z_\mathrm{K} = R_\mathrm{K} + \dfrac{1}{sC}$ уопштена *комплкенсна* импеданса

Решење (б) - испитује се знак реалног дела сигнум функције -- ово никако нема смисла када јој је у аргументу комплексан број, поље комплексних бројева није уређено. Овде би стандардно било разматрати само знак $\Re\\{z\\}$, сигнум је реално користан само као индикатор функција. Ово је могуће решити и заменом места сигнума и реалног дела, међутим, опет, бескорисно је.

Решење (в) - између једначина 61.6 и 61.7 -- преводи се у *комплкесни* домен

Решење (г) - између једначина 61.9 и 61.10 -- добија одзив у *Лаплсовом* домену

Коментар решења - претпоследња реченица првог пасуса - што доводи до *оваквног* одзива.

### Предлог
У коментару решења -- Ово може довести до проблема када се овакав систем користи у повратној спрези. Каквих проблема, зашто? Било би фино проширити задатак зарад потребе збирке, било то кроз други задатак номинално или наставком на овај да се прикаже макар Боде плот овог система, који је врло карактеристичан. Евентуално се може и спаковати на неки начин утицај фазе на closed loop стабилност. Може бити превише за СИС, међутим није тотално ван резона узети макар квалитативно овакву трансфер функцију и спаковати у задатке типа 35. Ако ништа, макар дати пример проблема који прави, решење се оставља за САУ/ЛЕ.

**Comment by budjen-jovan** [comment]
На други поглед, ово са знаком нуле можда и може да се провуче као директно поређење $z > 0$, односно $z < 0$ јер се зна да мора бити реална нула (једна је, полином је са реалним коефицијентима). Свакако, општије би било $\Re\\{z\\}$ поредити са нулом јер је ту јасно дефинисано да је поређење над реалним бројевима.

**Comment by djokicd** [comment]
Problem uređenosti skupa kompleksnih broejva rešen dodavanjem reči „реалан“. Ne vidim šta je problem sa sgn osim stilski?
Bode plot će verovatno ući u nekom trenutku u zbirku, ali to tek treba da se donese odluka. Kakvi problemi u NPS sa nulom u desnoj poluravni definitivno nisu tema za ovaj zadatak - samo je prokomentarisano jer je to inspiracija zadatka a između ostalog sam se i pozvao na SAU/LE.

**Comment by budjen-jovan** [comment]
Сигнум сам по себи овде ништа не ради, није нужно нетачно - ако већ посматрам реални део нуле, протеравање кроз сигнум само клемпује на ±1. Згодно је за убацити под интеграл у служби функције мере (на фору Лебеговог интеграла), овако је само дужи израз него што је потребно, највише је стилска примедба у принципу
