### ISSUE TITLE
Штампарскe грешкe у 60. задатку

### ISSUE THREAD

**Issue by budjen-jovan** [djokicd/zbirka-sis#38]
Код израчунавања ФТ по дефиницији прозороване експоненцијалне функције (једначина 60.1), у другом интегралу су границе постављене $t > \|T\|$, уместо $\|t\| > T$, шета се t, a не T.

У тексту између једначина 60.5 и 60.6 на почетку стоји тачка вишка испред почетка реченице; а и сама реченица би чини ми се требало да почиње са Покажимо, а не Покажемо.

Испод једначине 60.6 у коментару - искоришћена су парност sinc, и нормираност - мислим да је запета испред и вишак. Последња реченица нема тачку на крају.

**Comment by djokicd** [comment]
Што се тиче тог зареза то је апозиција.
