### ISSUE TITLE
Штампарска грешка у 63. задатку, предлог

### ISSUE THREAD

**Issue by budjen-jovan** [djokicd/zbirka-sis#39]
Решење под (б) - "То се дешава када је ***аругмент*** синусне функције у бројиоцу једнак $\pm \pi$". 

Са језичко-стилског становишта, мислим да би било лепше превести main lobe kao главни лук, што је и терминологија коришћена касније на ДОС.

Коментар на самом крају о дуалном понашању ширине прозора и спектра би било лепо прокоментарисати још мало - реченицу или две, јер је прилично значајан резултат. Сами детаљи апсолутно остају за ДОС касније, али било би фино мало јаче скренути пажњу на то, јер није занимљив фактоид него огромна ствар за прозорске функције касније. Како и шта рећи - нисам паметан, лако може да прерасте у ДОС предавање, не бих да коментаришем,

**Comment by djokicd** [comment]
дефинише се као  „лоб“ на антенама, али да, сећам се да је на ДОС било другачије...
