### ISSUE TITLE
Стилизација таблица у додатку

### ISSUE THREAD

**Issue by budjen-jovan** [djokicd/zbirka-sis#44]
Робијашке таблице у другој половини узете као еталон (јер су најчитљивије):

- у првој (таблица конволуција континуалних сигнала) фале хоризонталне линије, које заиста помажу код раздвајања јер су гадни изрази, поготово са малим размаком између њих.
- у другој (таблица конволуција дискретних сигнала) све исто, мада је ово читљиво и без хоризонталних линија
- у трећој (таблица формалних развоја) све исто као у претходном
- у четвртој (ако се може назвати таблицом, јер нема таблице - интеграли) - фали таблица

Ако већ стоје дефиниције конволуција дискретних и континуалних сигнала у таблици, било би фино да и трансформације и развоји у редове добију своје дефиниције.

**Comment by djokicd** [comment]
Уведен је додатак који се односи на особине трансформација.
