### ISSUE TITLE
10 zadatak, pomereni dijagrami za a) i v)

### ISSUE THREAD

**Issue by devdavest** [djokicd/zbirka-sis#5]
*Lokacija*
10 zadatak pod a) (resenje)

*Problem*
Dijagram krece od n=1

*Resenje*
Dijagram treba da krece od n=0

*Lokacija*
10 zadatak pod v) (resenje)

*Problem*
Dijagram je prikazan za (1 - n) * (u[n+1] - u[n-4])

*Resenje*
Da bi bilo resenje postavke zadatka, potrebno je ubaciti odbirak na n=-2 visine 3, i obrisati odbirak na n=3

**Comment by djokicd** [comment]
A jesam idiotski ovo napisao....
```
def u(t):
    return (t > 0) * 1.0
```
