### ISSUE TITLE
17. Zadatak, numeracija

### ISSUE THREAD

**Issue by budjen-jovan** [djokicd/zbirka-sis#9]
U 17. zadatku (moguce i na drugim mestima, nisam video) stoje zadaci a), b), g) (preskoceno - zakomentarisano v))

Potencijalno resenje je 
\begin{enumerate}[label=\alph*)]
    \item
    \item
    ...
    \item
\end{enumerate}

sto automatski numerise cirilicnim slovima redom kako je napisano bez rucnog obelezavanja (u preambuli je vec babel serbianc podesen i importovan je enumitem).

Za taj konkretan zadatak mogu da otvorim PR, medjutim trebalo bi to onda uraditi u citavom dokumentu zarad konzistentnosti, sto u principu nije nemoguce, ali necu nista da radim ovog kalibra bez saglasnosti, da ne bacim posao u vodu

**Comment by djokicd** [comment]
Pošto zagrada treba sa obe strane, komandu sam ovako prekrstio:
`\begin{enumerate}[label=(\alph*)]`
ali da, ovo je svakako trebalo uraditi, ali sam ja zaboravio kako to može. Hvala!
